### PR TITLE
[typescript] introduce typescript tests

### LINKED ISSUE #108: Avoid TS regressions (final-form and react-final-form defs are not in sync)
### Are you submitting a **bug report** or a **feature request**?

Both :)

### What is the current behavior?

In fact the typescript definition file is not tested and I tkink it leads easily to regressions.

Since last release of both final-form and react-final-form, I get this...

image

### Other information

On definitively repository, ts definitions files are tested against an example called test.ts, covering every use cases (only syntax), I think it is the way to solve it.

I know that you don't write TS yourself but it could be really nice.

### LINKED ISSUE #125: 3.0.2 typescript error TS2322 on subscriptions
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?
I introduced changes in https://github.com/final-form/final-form/pull/61 that produce typescript errors.

### What is the expected behavior?
One example:

```
error TS2322: Type '{ subscription: { errors: true; values: true; }; children: (form: FormSpyRenderProps) => Element; }' is not assignable to type 'IntrinsicAttributes & FormSpyProps & { children?: ReactNode; }'.
  Type '{ subscription: { errors: true; values: true; }; children: (form: FormSpyRenderProps) => Element; }' is not assignable to type 'FormSpyProps'.
    Types of property 'subscription' are incompatible.
      Type '{ errors: true; values: true; }' is not assignable to type 'FormSubscription'.
        Property 'active' is missing in type '{ errors: true; values: true; }'.
```

### What's your environment?
 final-form        ^4.0.1 
 react-final-form  ^3.0.2 

### Other information
I created the problem, I'll PR the fix ASAP.  Working on it now.  I will probably PR tests here as well (Closes #108)

### PR DESCRIPTION
**Pull request by rosskevin**
Depends on https://github.com/final-form/final-form/pull/66
Closes #125 
Closes #108 

Adds typescript tests to validate common usage.

### CODE REVIEW

**Comment by rosskevin** [comment]
4.0.2 appears to be missing the changes https://github.com/final-form/final-form/pull/66#issuecomment-358415697

**Comment by rosskevin** [comment]
@erikras I'm not sure what makes the other line changes in package.json, but they are unintentional.  I think perhaps prettier is?  It's not a bad thing, I was just wondering why I keep having more lines changed than expected.

**Comment by erikras** [comment]
Published in [`v3.0.4`](https://github.com/final-form/react-final-form/releases/tag/v3.0.4).

**Comment by brikou** [comment]
@rosskevin thanks for your work :+1:

**Pull request merged**
