### PR TITLE
Move examples to the repo

### PR DESCRIPTION
**Pull request by Andarist**
Examples will be available under similar URLs - https://codesandbox.io/s/github/Andarist/react-final-form/tree/examples/examples/simple .

IMHO it would make it easier to manage them (having them all in the repo), add more etc.

Downsides? Lost views etc, but maybe there is some option to "migrate" sandbox ids? cc @CompuIves

### CODE REVIEW

**Comment by CompuIves** [comment]
I can try to move the sandbox ids to the GitHub equivalents. I think it should be doable from the top of my head, but can't promise anything!

**Comment by Andarist** [comment]
Hm, maybe not worth it then? I thought it might already be doable by configuring it with `codesandbox.json` (or similar, dont remember exact file name)

**Comment by erikras** [comment]
Holy crap! You really went and copied all that code into files?

I considered doing this when CodeSandbox got its Github integration. I guess the main upside would be allowing PRs to the examples? And just safer code. Once I thought I had forked the Simple Example and saved over it, requiring me to build it again from memory.

Have either of you seen other repos doing this?

**Comment by Andarist** [comment]
> Holy crap! You really went and copied all that code into files?

Yeah, kinda... 😆 I've automated some of the process, but still took some time (wasnt that bad though 😉 )

> I considered doing this when CodeSandbox got its Github integration. I guess the main upside would be allowing PRs to the examples? And just safer code.

Yeah, PRs are the main benefit - but also keeping their history in git etc.

> Have either of you seen other repos doing this?

In example redux - https://github.com/reduxjs/redux#examples

**Comment by erikras** [comment]
> I can try to move the sandbox ids to the GitHub equivalents. I think it should be doable from the top of my head, but can't promise anything!

Does this mean that old links would/could still work?

**Comment by Andarist** [comment]
> Does this mean that old links would/could still work?

I think yes - because if you enter the example link ( https://codesandbox.io/s/github/Andarist/react-final-form/tree/examples/examples/simple ) you'll see an ID assigned to it and you can enter the same sandbox through the url with ID ( https://codesandbox.io/s/53y92vk1p4 in this case )

What we would need here is to tie those github URLs with original IDs (i think its not possible without Ives' help)

**Comment by erikras** [comment]
> What we would need here is to tie those github URLs with original IDs (i think its not possible without Ives' help)

Well, the mapping is pretty easy to see [here](https://github.com/final-form/react-final-form/pull/308/files#diff-04c6e90faac2675aa89e2176d2eec7d8). @CompuIves, got an intern minion you can delegate this to? 😄

**Comment by Andarist** [comment]
Extracted this by querying the diff
```
ww40y2m595 - github/final-form/react-final-form/tree/master/examples/simple
yk1zx56y5j - github/final-form/react-final-form/tree/master/examples/sync-record-validation
2k054qp40 - github/final-form/react-final-form/tree/master/examples/sync-field-validation
wy7z7q5zx5 - github/final-form/react-final-form/tree/master/examples/async-field-validation
kl9n295n5 - github/final-form/react-final-form/tree/master/examples/hybrid-record-validation
9y9om95lyp - github/final-form/react-final-form/tree/master/examples/submission-errors
40mr0v2r87 - github/final-form/react-final-form/tree/master/examples/third-party-components
2z5y03y81r - github/final-form/react-final-form/tree/master/examples/material-ui-v1
32r824vxy1 - github/final-form/react-final-form/tree/master/examples/perf-through-subscriptions
xoo3xq654p - github/final-form/react-final-form/tree/master/examples/independent-error-component
91w9ro3x9o - github/final-form/react-final-form/tree/master/examples/loading-and-initializing
kx8qv67nk5 - github/final-form/react-final-form/tree/master/examples/field-arrays
oq52p6v96y - github/final-form/react-final-form/tree/master/examples/calculated-fields
m5qwxpr6o8 - github/final-form/react-final-form/tree/master/examples/field-warnings
8z5jm6x80 - github/final-form/react-final-form/tree/master/examples/reusable-field-groups
1y7noyrlmq - github/final-form/react-final-form/tree/master/examples/external-submit
km2n35kq3v - github/final-form/react-final-form/tree/master/examples/wizard-form
10rzowm323 - github/final-form/react-final-form/tree/master/examples/parse-and-format
5w4yrpyo7k - github/final-form/react-final-form/tree/master/examples/auto-save-debounce
7k742qpo36 - github/final-form/react-final-form/tree/master/examples/auto-save-field-blur
kxxw4l0p9o - github/final-form/react-final-form/tree/master/examples/custom-validation-engine
xr0mvl1904 - github/final-form/react-final-form/tree/master/examples/load-save-reinitialize
qzm43nn2mj - github/final-form/react-final-form/tree/master/examples/downshift
4xq2qpzw79 - github/final-form/react-final-form/tree/master/examples/redux
lm4p3m92q - github/final-form/react-final-form/tree/master/examples/conditional-fields
3x989zl866 - github/final-form/react-final-form/tree/master/examples/external-changes
6174kqr403 - github/final-form/react-final-form/tree/master/examples/focus-error
9y8vkrrx9o - github/final-form/react-final-form/tree/master/examples/credit-card
x71mx66z8w - github/final-form/react-final-form/tree/master/examples/redux-async-submission
52q597j2p - github/final-form/react-final-form/tree/master/examples/declarative-form-rules
no20p7z3l - github/final-form/react-final-form/tree/master/examples/format-string-by-pattern
5m4w2909k - github/final-form/react-final-form/tree/master/examples/redux-async-typeahead
3rp260ly51 - github/final-form/react-final-form/tree/master/examples/format-on-blur
40o45po3l4 - github/final-form/react-final-form/tree/master/examples/smooth-ui
```

**Comment by erikras** [comment]
🤣 Just give @Andarist the names of the tables and columns and he'll write the SQL script for ya!

```sql
UPDATE sandbox
  SET githubUrl='final-form/react-final-form/tree/master/examples/simple'
  WHERE id='ww40y2m595';
```

**Pull request closed without merging**
