### PR TITLE
feature/persistentSubmitErrors added persistentSubmitErrors prop

### PR DESCRIPTION
**Pull request by alex-shatalov**
final-form/final-form#77

### CODE REVIEW

**Comment by erikras** [comment]
What does this accomplish? Can you give more explanation?

**Comment by erikras** [comment]
Sorry, I had not seen https://github.com/final-form/final-form/pull/77/. You should have linked to it for clarity.

**Comment by alex-shatalov** [comment]
We have case that we need to submit form even if it has validation errors. So when we submitting form it fails on hasSyncErrors() in submit.  In redux form prop persistentSubmitErrors helps us to avoid this problem. 

Maybe you could give advise how to get it without this changes in pull request. Thanks.

**Comment by erikras** [comment]
> Maybe you could give advise how to get it without this changes in pull request. Thanks.

Sounds like you're looking for [Field Warnings](https://github.com/final-form/react-final-form#field-warnings).

**Pull request closed without merging**
