### PR TITLE
Lock handleSubmit while submitting

### PR DESCRIPTION
**Pull request by Andarist**
Actually this probably could be included in final-form itself. If you'd like to include this change, let me know in which package and I'll update my PR (or move it) appropriately. I might also write tests once you approve the logic

### CODE REVIEW

**Comment by erikras** [comment]
So this is just `submit() { if(submitting) { return } ..... }` logic?

**Comment by erikras** [comment]
...and yes, FF is the place for this.

**Comment by Andarist** [comment]
> So this is just submit() { if(submitting) { return } ..... } logic?

Yeah, total brain fart, lol. I've kinda copy pasted what I've put into my app to handle this (as I dont get easy access to the FF state from outside of the <ReactFinalForm/>). Totally missed the obvious fact that I can actually use the FF state here 😅

**Comment by erikras** [comment]
Published fix in [`final-form@4.13.0`](https://github.com/final-form/final-form/releases/tag/v4.13.0).

**Pull request closed without merging**
