### PR TITLE
Reproduced the bug with async validation on filed when resolve promise immediately

### PR DESCRIPTION
**Pull request by BataevDaniil**
I reproduced in test error when async validation on field when resolve promise immediately when add new field.
I don`t know how this fix.

### CODE REVIEW

**Comment by erikras** [comment]
This test is not `expect`ing anything. I don't really understand the problem. Can you make it fail?

**Comment by BataevDaniil** [comment]
> This test is not `expect`ing anything. I don't really understand the problem. Can you make it fail?

I didn't find an opportunity to catch "unhandled promise rejection" in jest. You can see the log in the terminal.
Example
```
(node:47480) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'active' of undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:47480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:47480) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'active' of undefined
(node:47480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
еще локально на второй render component я получаю ошибку validating get from undefined

**Comment by BataevDaniil** [comment]
Hello, @erikras

**Comment by BataevDaniil** [comment]
Hello, @erikras

**Comment by erikras** [comment]
What am I supposed to see when I load up your codesandbox? Clicking the button makes the other fields appear. I'm not seeing any errors.

**Comment by jarnaiz** [comment]
Hello @erikras  & @BataevDaniil 

Im getting this error in versions:
- final-form: 4.20.6
- react-final-form: 6.5.8

The codesandbox: https://codesandbox.io/s/react-final-form-asynchronous-field-level-validation-example-forked-v1ktoy?file=/index.js

**Comment by jarnaiz** [comment]
Hello again!

Here you have a workaround:
https://codesandbox.io/s/react-final-form-asynchronous-field-level-validation-example-workaround-po5eq1

Pausing the validation process before register the new Field and resume it after the rerender, should fix the problem.

**Comment by jarnaiz** [comment]
This bug is fixed with final-form: 4.20.9 :D

**Comment by gertdreyer** [comment]
Closing as per @jarnaiz 

> This bug is fixed with final-form: 4.20.9 :D

Feel free to reopen if the issue has not been resolved

**Pull request closed without merging**
