### PR TITLE
Fix parse and format TS defs (as not required)

### PR DESCRIPTION
**Pull request by brikou**
Please release a fix :)

### CODE REVIEW

**Comment by erikras** [comment]
You're 100% sure this is right? I tried putting those `?`s in Flow and things broke because of `defaultProps`.

**Comment by brikou** [comment]
@erikras give me 5 mins, I'll confirm it (or not...)

**Comment by erikras** [comment]
Tick....tock.... 😜⏱️

**Comment by brikou** [comment]
Yes sure, my patch clear this ugly message

image

**Comment by brikou** [comment]
Thanks @erikras and your lib rocks (migrating from formik...) :1st_place_medal:

**Comment by erikras** [comment]
Published in [`v2.1.1`](https://github.com/final-form/react-final-form/releases/tag/v2.1.1).

Fast enough for ya? 😀

**Comment by brikou** [comment]
Great!!!!

**Pull request merged**
