### PR TITLE
Forward refs to input component

### LINKED ISSUE #141: Get Field Component via refs
### Are you submitting a **bug report** or a **feature request**?
feature request

### What is the current behavior?
There is no a way to get Field components via refs.

### What is the expected behavior?
Access to the rendered component in a Field `<Field {....} component={MyCustomField} />`.

### What's your environment?
- final-form": "^4.2.0"
- react-final-form": "^3.1.0

### Other information
I am using this library in a React Native App, so the behavior that I would like to implement is this: Focus a field when clicking on "Next" key in the virtual keyboard on iOS.

### PR DESCRIPTION
**Pull request by TylerRick**
Resolves #141 

Still to do:
- [x] Make the same change to Field in `react-final-form-html5-validation` (final-form/react-final-form-html5-validation#18)
- [x] Add a test
- [x] Update docs
- [ ] Get Flow typings to work in Field.js

### CODE REVIEW

**Comment by ivchenkodima** [comment]
Any updates?

**Comment by kopax** [comment]
can we get this released? This is so much needed in react native for the user experience: https://stackoverflow.com/questions/32748718/react-native-how-to-select-the-next-textinput-after-pressing-the-next-keyboar 

I don't need flow validation I don't use typescript, is there a fork I can use to get this working?

**Comment by kopax** [comment]
Someone really needs to kick this, it can't be a major fix and being stuck for soon a year.

**Comment by kopax** [comment]
Thanks @erikras for taking care of it, that is somehow super important and I appreciate you took care of our remarks. Do you think this will be released soon?

**Comment by erikras** [comment]
I hope so. Flow has been a real pain for the past couple of years, blocking solid PRs like this one. At some point, FF and RFF will need to be rewritten into Typescript and Flow support dropped.

**Comment by erikras** [comment]
@kopax In your opinion, does this merge alleviate the need for #781?

**Comment by kopax** [comment]
Yes, this was to push a little bit, I will close this PR, and also https://github.com/final-form/react-final-form/issues/779 as soon as we can test the new feature and validate it as fixed.

**Comment by kopax** [comment]
It seems that the CI prevent the release for being done: https://travis-ci.org/github/final-form/react-final-form/jobs/676834260 , perhaps https://github.com/final-form/react-final-form/issues/141 should be kept open until it's done?

**Comment by kopax** [comment]
@erikras any update on that one? Perhaps it's possible to drop Flow type on just that file? Or at leaste release one version in a nighty channel?

**Comment by Nnanyielugo** [comment]
It doesn't seem like this release made it through. Is there a way this could be pushed through?
I had to use `redux form` for the one form that needed refs, and it seems a little too hackish.

Would be nice if this was looked into.

**Comment by kopax** [comment]
@Nnanyielugo this is the issue for tracking, https://github.com/final-form/react-final-form/issues/483 

I am also expecting to see this soon, I was about to remove RFF before they merged this. Any plan for this ?

**Comment by erikras** [comment]
Apologies for the delay. Since this was merged, I gave two conference workshops, one conference talk, and started two new jobs. Publishing today...

**Comment by erikras** [comment]
Published in [`v6.5.0`](https://github.com/final-form/react-final-form/releases/tag/v6.5.0).

**Comment by kopax** [comment]
thanks for the release ! I would like to know if anyone have tested it ? Passing `const ref = useRef();` to the `<Field ref={ref} />` does not save the ref as I expect.

**Comment by SpadarShut** [comment]
@kopax I confirm, passing ref to field does not set `current` to input, but instead sets it to the field instance.

**Comment by SpadarShut** [comment]
Looks like the output of `react-final-form-html5-validation.es.js` does not contain the chenges from this PR.

**Comment by kopax** [comment]
is this now fixed and in which versIons?

**Pull request merged**
