### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gtournie**
Add redux-form-validators code sandboxes

### CODE REVIEW

**Comment by erikras** [comment]
@gtournie Can you fix your "alphanumeric" validation in the sandbox?

```js
      with: /^[a-zA-Z0-9 ]$/i,
```
should be:
```js
      with: /^[a-z0-9 ]*$/i,
```
(no need for `A-Z` because it's already case insensitive)

**Comment by erikras** [comment]
@gtournie ping.

**Comment by gtournie** [comment]
@erikras Fixed. Sorry for the delay.

**Comment by erikras** [comment]
[Not for `username`](https://codesandbox.io/s/y43o4vqj1).

**Pull request closed without merging**
