### PR TITLE
feat: export context

### LINKED ISSUE #745: export context, cant use hooks in class components nor events
### submitting a **feature request**?

It would be great to consume the context directly.

> You can’t use Hooks inside of a class component,
https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both

> Call Hooks from React function components.
> Do not call Hooks in class components.
> Do not call in event handlers.
https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions

### What is the current behavior?

No direct access to context, not exported.
And can't use hooks in class components.

### What is the expected behavior?

direct access to context by exporting it, to support access within class components too.

```js
import { ReactFinalFormContext } from 'react-final-form';
```

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #745

### CODE REVIEW

**Comment by erikras** [comment]
Why? `useForm` gives you everything you could need.

**Comment by AndyOGo** [comment]
Because hooks cant be used within class components, context types can.

> You can’t use Hooks inside of a class component,
https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both

**Comment by AndyOGo** [comment]
@erikras did you got my feedback?

**Comment by erikras** [comment]
I think I'd still rather not. It's easy enough to inject into props with a HOC.

```jsx
const withForm = Component => props => (
  <FormSpy subscription={{}}>
    {({ form }) => <Component {...props} form={form} />}
  </FormSpy>
)
```

**Comment by AndyOGo** [comment]
You are right, it's easy to write a custom `withForm` HoC.
Same is true for this change, it's a one liner, will not affect bundle size and is conform to React Context API. But I can see if you may decide to replace underlying context with something else in the future, this change would introduce problems.

Anyway, thanks for your great work!

Nevertheless it's may also just personal taste, imho I would prefer to consume the context directly.

**Comment by erikras** [comment]
Yeah, my sense is that the context variable should remain internal to the library.

Thanks for your totally reasonable suggestion, though. ❤️

**Pull request closed without merging**
