### PR TITLE
Unify TS tests & backport removed typing improvements

### PR DESCRIPTION
**Pull request by Andarist**
It seems that my PR was somewhat conflicting with the other one that got merged in before mine - https://github.com/final-form/react-final-form/pull/388 . Both have introduced TS tests so I went ahead and unified both, which means that I basically moves the other tests from `src` to `typescript` dir.

While doing this I've noticed that you have resolved conflicts in a wrong way, so I've reintroduced what was missing:
https://github.com/final-form/react-final-form/commit/49b632e7db291c89f31ab9611dcc3d2e4fe3a7b1
https://github.com/final-form/react-final-form/commit/2fe9f190104bab90dc1a5d54fb55b26c26853a3a
https://github.com/final-form/react-final-form/commit/e01de8583d37f6f031f9320d8e3b4d336a043d21

### CODE REVIEW

**Comment by erikras** [comment]
This pull request **introduces 5 alerts** and **fixes 5** when merging d4c6409826b6c9df2279ddca2cbda65e3969ddd4 into d68a91feb58cd6a794e0a215fb8a33b3bd4b83b5 - [view on LGTM.com](https://lgtm.com/projects/g/final-form/react-final-form/rev/pr-09638079c91380ac658cc5a9dff10c9230f52b83)

**new alerts:**

* 5 for Unused variable, import, function or class

**fixed alerts:**

* 5 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Andarist** [comment]
Again - this has some warnings regarding unused variables, but actually they are supposed to be unused. I'm not sure how to fix this - seems like lint config responsible for this lives in LGTM config and I cant edit this as part of my PR

**Comment by erikras** [comment]
Ugh.  LGTM seems to cause more trouble than it's worth.

I'm not sure why it comments as me. 😡

**Comment by erikras** [comment]
Thanks. Yes, the fact that you moved the tsconfig to another directory caused me some headaches yesterday. Thanks for the repairs.

**Comment by erikras** [comment]
https://github.com/final-form/react-final-form/commit/a3ca5f169da5cb5abcf53d60285d8d43b08c427f seems to have fixed the tslint errors. Apparently the tslint defaults aren't the same as my preferred prettier settings.

**Comment by valerybugakov** [comment]
@erikras would you mind releasing new version with these typing fixes?

**Pull request merged**
