### PR TITLE
Add simple test for generic FieldRenderProps type

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by erikras** [comment]
This pull request **introduces 2 alerts** when merging 1e1d5fe4f8323301edaf74100cd5d00bf26258bb into a3ca5f169da5cb5abcf53d60285d8d43b08c427f - [view on LGTM.com](https://lgtm.com/projects/g/final-form/react-final-form/rev/pr-2ad9b948c0ea095dee4f6782d341c58da851cc74)

**new alerts:**

* 2 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by erikras** [comment]
This pull request **introduces 2 alerts** when merging 0697fd6546a58fddadec1549b312aaab3c63398d into a3ca5f169da5cb5abcf53d60285d8d43b08c427f - [view on LGTM.com](https://lgtm.com/projects/g/final-form/react-final-form/rev/pr-1af16e1e4c758d2bf003095416dd8c5f31190699)

**new alerts:**

* 2 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by erikras** [comment]
Can't `ts-essentials` be a dev dependency?

**Comment by Andarist** [comment]
Not rly, because the imported thing would have to be inlined during build, but .d.ts files are distributed as is (building them anyhow when the source is not authored in TS would be a huge overkill). 

We could inline manually this implementation, but personally I find it counter-productive.

**Comment by erikras** [comment]
I'm correct in assuming that we could add a hundred different type helper libs as dependencies, and it would have no effect whatsoever on the final bundle size the browser sees, because TS is _entirely_ build-time, right?

**Comment by vladshcherbin** [comment]
@erikras I believe this is not correct, adding TS packages to `dependencies` will install unnecessary packages for devs who are not using TS.

This is what I found out when tried to add types to one of my packages. For js projects, adding types to `@types` repo is a much better solution and [is recommended](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) in TS docs.

**Comment by erikras** [comment]
This pull request **introduces 2 alerts** when merging 9c5cdad752f831c4cc97593e8ce08c5a03928f55 into 7315a3a95ee0fe645bacc84a0243e417a3fb6458 - [view on LGTM.com](https://lgtm.com/projects/g/final-form/react-final-form/rev/pr-94e88b139be9d19e81b2497775a171616e711cc2)

**new alerts:**

* 2 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by erikras** [comment]
Published in [`v5.1.1`](https://github.com/final-form/react-final-form/releases/tag/v5.1.1).

**Pull request merged**
