### PR TITLE
Updated material-ui demo

### LINKED ISSUE #362: Material-UI 3.x example
Please do an example that demonstrates how to use [Material-UI 3.x](https://material-ui.com/) input components.

### PR DESCRIPTION
**Pull request by eps1lon**
The updated codesandbox can be found under https://codesandbox.io/s/3190284lv5. Since @erikras is the owner of the original codesandbox he would have to pull in changes.

- some props were moved from the root to `inputProps`
- `InputProps` -> `inputProps` for the selection controls
- `!!checked` -> `Boolean(checked)` (clearer intent)

Closes #362

### CODE REVIEW

**Comment by popugang** [comment]
InputProps -> inputProps not true, because the field name animation does not work

When InputProps we see right display
image

When inputProps we see not correct display
image

**Comment by eps1lon** [comment]
For `TextField` you are correct. Will fix it.

**Comment by oliviertassinari** [comment]
Something I have done some time ago: https://codesandbox.io/s/9ywq085k9w.

**Comment by erikras** [comment]
Thanks!

**Comment by oliviertassinari** [comment]
@erikras We have been working on updating the codesandbox demo: https://codesandbox.io/s/9ywq085k9w. I wish we could point people to this implementation. I see 3 options:
1. You do nothing, we only reference the demo on Material-UI side.
2. You keep the ownership of the codesandbox, maybe by forking the linked version.
3. You move the ownership of the demo to Material-UI.

What do you prefer?

**Comment by erikras** [comment]
@oliviertassinari I recognized your name and avatar, but it didn't click that you were the MUI guy. I'd be happy for you guys to maintain that demo. I'll change the link.

**Comment by oliviertassinari** [comment]
@erikras Thank you! I will do my best to keep it up to date :)

**Comment by aikidoshi** [comment]
@oliviertassinari Could you please do us all a favour and add a date picker to you example? That always seems to get left out.

**Comment by oliviertassinari** [comment]
@aikidoshi Done. But keep track of https://github.com/Deadly0/final-form-material-ui/issues/7.

**Comment by oliviertassinari** [comment]
https://twitter.com/olivtassinari/status/1100159177681448966

**Comment by aikidoshi** [comment]
@oliviertassinari Wow! That is fantastic, thanks! Final Form is a game changer for me and this will give me a whole new look and feel as well. Thanks again.

**Pull request merged**
