### PR TITLE
Issue 175: pass any additional props to custom component

### PR DESCRIPTION
**Pull request by Th0rN13**
This PR for resolve [issue #175](https://github.com/final-form/react-final-form/issues/175)

Now u can add any additional props to your custom component. I use custom Select, so i need to pass label, options and anyAdditionalProp.

### How to use

**RenderForm.tsx**
```
<Field<string>
  name="stack"
  component={SelectAdapter}
  label="Tools"
  options={optionsArrayVariable}
  anyAdditionalProp={anyAdditionalProp}
/>
```

**FormAdapters.tsx (contain adapters for custom components)**
```
interface SelectAdapterProps extends HTMLElement {
  label?: string;
  options: Option[];
  anyAdditionalProp: any;
}

export const SelectAdapter = (props: FieldRenderProps<string, SelectAdapterProps>) => {
  const {
    input,
    meta,
    ...rest
  } = props;
  const {
    options,
    label,
    anyAdditionalProp,
  } = input;
  return (
    <Select
      options={options}
      label={label || ''}
      anyAdditionalProp={anyAdditionalProp}
      {...input}
      {...rest}
    />
  );
};
```

### CODE REVIEW

**Comment by po35** [comment]
Thanks for this PR but tbh, we need really some more docs around this (<Field<string>...., FieldRenderProps<string, SelectAdapterProps>, ...extends HTMLElement) Even when I follow your example TS sends errors in my code. Just comparing formik and rff and the type system there (IDK if better or worse) feels somehow more accessible. There I just gave my custom field a type paired with an interface for the props and all fine.  Sorry that I don't have more time to put every error TS gave me. But as said said we should start documenting why @Th0rN13 went the way above in the first place. Thx  CCing @erikras

**Comment by Yankovsky** [comment]
@erikras @Th0rN13 same fix is needed for react-final-form-arrays package.

**Comment by Yankovsky** [comment]
@Th0rN13 @erikras I still have the same issue https://codesandbox.io/s/strongly-typed-form-values-with-react-final-form-ewnfh

**Comment by erikras** [comment]
Published in [`v6.3.1`](https://github.com/final-form/react-final-form/releases/tag/v6.3.1).

**Pull request merged**
